version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "0.15.3"
    TF_COMMAND: "destroy"


phases:
  install:
    runtime-versions:
      python: 3.9
    on-failure: ABORT
    commands:
      - sudo yum update -y && sudo yum install -y jq
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/

  pre_build:
    commands:
      - echo "Fetching AWS credentials from Secrets Manager..."
    - aws secretsmanager get-secret-value --secret-id CodeBuildAWSKeys --query SecretString --output text
    - export SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id CodeBuildAWSKeys --query SecretString --output text)
    - echo "Extracted Secret: $SECRET_JSON"
    - export AWS_ACCESS_KEY_ID=$(echo $SECRET_JSON | jq -r '.AWS_ACCESS_KEY_ID')
    - export AWS_SECRET_ACCESS_KEY=$(echo $SECRET_JSON | jq -r '.AWS_SECRET_ACCESS_KEY')
    - echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
    - echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
      - aws sts get-caller-identity

  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init -backend-config="bucket=$TF_BUCKET" -backend-config="dynamodb_table=$TF_DYNAMODB_TABLE"
      - terraform validate
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform..."
      - terraform apply -auto-approve tfplan
