version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "0.15.3"
    TF_COMMAND: "apply"
  parameter-store:
    AWS_ACCESS_KEY_ID: "/CodeBuild/MY_AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "/CodeBuild/MY_AWS_SECRET_ACCESS_KEY"


phases:
  install:
    runtime-versions:
      python: 3.9
    on-failure: ABORT
    commands:
      - sudo yum update -y && sudo yum install -y jq
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/


  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init -backend-config="bucket=$TF_BUCKET" -backend-config="dynamodb_table=$TF_DYNAMODB_TABLE"
      - terraform validate
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform..."
      - terraform $TF_COMMAND  --auto-approve
