version: 0.2

phases:
  install:
    commands:
      - echo "Installing AWS CLI and Terraform..."
      - yum install -y jq
      - sudo apt update && sudo apt install wget -y
      - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update && sudo apt install -y terraform

  pre_build:
    commands:
      - echo "Fetching AWS credentials from Secrets Manager..."
      - export AWS_ACCESS_KEY_ID=$(aws secretsmanager get-secret-value --secret-id CodeBuildAWSKeys --query SecretString --output text | jq -r .AWS_ACCESS_KEY_ID)
      - export AWS_SECRET_ACCESS_KEY=$(aws secretsmanager get-secret-value --secret-id CodeBuildAWSKeys --query SecretString --output text | jq -r .AWS_SECRET_ACCESS_KEY)
      - aws sts get-caller-identity

  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init -backend-config="bucket=$TF_BUCKET" -backend-config="dynamodb_table=$TF_DYNAMODB_TABLE"
      - terraform validate
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform..."
      - terraform apply -auto-approve tfplan
